trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureMonitorAlerts@1
    inputs:
      resourceGroupName: 'MyResourceGroup'
      alertRulesName: 'CPU_Usage_High'
