trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Your-Azure-Subscription-Name'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az monitor metrics alert create \
          --name 'CPU_Usage_High' \
          --resource-group 'MyResourceGroup' \
          --scopes '/subscriptions/{subscription-id}/resourceGroups/MyResourceGroup/providers/Microsoft.Compute/virtualMachines/MyVM' \
          --condition "avg Percentage CPU > 80" \
          --description 'Alert when CPU usage exceeds 80%' \
          --action-group '/subscriptions/{subscription-id}/resourceGroups/MyResourceGroup/providers/microsoft.insights/actionGroups/MyActionGroup'
    displayName: 'Create CPU Alert'
